name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-test:
    uses: ./.github/workflows/_build-test.yml
    secrets: inherit

  quality-gate:
    needs: build-test
    uses: ./.github/workflows/_quality-gate.yml
