name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-test:
    uses: ./.github/workflows/_build-test.yml
    with:
      os: windows-latest
    secrets: inherit

  quality-gate:
    needs: build-test
    uses: ./.github/workflows/_quality-gate.yml
    with:
      os: windows-latest

  mutation:
    needs: build-test
    if: github.event_name == 'pull_request'
    uses: ./.github/workflows/_mutation.yml
    with:
      os: windows-latest
