name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main, develop]

jobs:
  build-test:
    uses: ./.github/workflows/_build-test.yml
    with:
      os: windows-latest
    secrets: inherit

  quality-gate:
    needs: build-test
    uses: ./.github/workflows/_quality-gate.yml
    with:
      os: windows-latest
